Algoritmo COMPRÁ_IVA
	Definir UNI,VALOR_UNI,TOTALB,TOTALN Como Entero
	Definir IVA	 Como Real
	Definir NOMBRE Como Caracter
	Escribir  "BIENVENIDO AL PROGRAMA ARa NOSOTROS APLICAMOS EL IVA"
	Escribir  "DIME EL PRODUCTO"
	Leer NOMBRE
	Escribir "CUANTOS SON DE ESTOS SON?"
	Leer UNI
	Escribir "DIGITE EL VALOR UNITARIO DEL UNITARIO"
	Leer VALOR_UNI
	TOTALB<-UNI*VALOR_UNI
	TOTALN<-(TOTALB*0.19)+TOTALB
	Escribir  "USTE´COTIZO A " NOMBRE " CON UNA CANTIDA DE " UNI " Y CUESTA CADA UNA, $ " VALOR_UNI " EL TOTAL ES DE $ " TOTALB
	Escribir "EL VALOR DE EL PRODUCTO CON IVA DE 19% E:$" TOTALN
FinAlgoritmo
